name 'oracle-weblogic-lifecycle'
maintainer 'Shinya Yanagihara'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures oracle-weblogic-lifecycle'
long_description 'Installs/Configures oracle-weblogic-lifecycle'
version '0.1.0'
